In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [40]:
# Load it into a Jupyter Notebook.
diabetes_df = pd.read_csv('diabetes.csv', header=None,)


In [41]:
# Exploring the dataset

diabetes_df.columns = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'outcome']

In [42]:
diabetes_df

pregnant  glucose             bp           skin  insulin   bmi  \
0    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI   
1              6      148             72             35        0  33.6   
2              1       85             66             29        0  26.6   
3              8      183             64              0        0  23.3   
4              1       89             66             23       94  28.1   
..           ...      ...            ...            ...      ...   ...   
764           10      101             76             48      180  32.9   
765            2      122             70             27        0  36.8   
766            5      121             72             23      112  26.2   
767            1      126             60              0        0  30.1   
768            1       93             70             31        0  30.4   

                     pedigree  age  outcome  
0    DiabetesPedigreeFunction  Age  Outcome  
1                       0.627   50        1  
2                       0.351   31        0  
3                       0.672   32        1  
4                       0.167   21        0  
..                        ...  ...      ...  
764                     0.171   63        0  
765                      0.34   27        0  
766                     0.245   30        0  
767                     0.349   47        1  
768                     0.315   23        0  

[769 rows x 9 columns]

In [43]:
X = diabetes_df.drop('outcome', axis=1)# Exclude target
X = X.values
y = diabetes_df['outcome'] # Extract the target
y = y.values

In [44]:
# Split the data into training and testing data using the train_test_split function
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.33,
                                                    random_state=7)

# Decision Tree

In [45]:
# Train a decision tree classifier that is pruned at a depth of 6.¶
from sklearn.tree import DecisionTreeClassifier
clf_d=DecisionTreeClassifier(max_depth=6, random_state=0) 
clf_d.fit(X_train, y_train)

ValueError: could not convert string to float: 'Pregnancies'

In [32]:
# Visualise the tree
from sklearn import tree
diabetesfig=plt.figure(figsize=(15,10))
_=tree.plot_tree(clf_d,filled=True,feature_names=X_train.columns)
# save to file
diabetesfig.savefig("diabetestree.png")

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

<Figure size 1080x720 with 0 Axes>

In [ ]:
# The accuracy score for Decision Tree
from sklearn import metrics
print("Accuracy on the training set:", clf_d.score(X_train, y_train))
print("Accuracy on the test set :", clf_d.score(X_test, y_test))

In [24]:
# Make a prediction for the person with the following information: 3, 125, 68, 30, 120, 37, 0.4, 28.

# Predict age of new abalone
import numpy as np
X_new = np.array([[3,125,68,30,120,37,0.4,28]])
pred1= clf_d.predict(X_new)


NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [54]:
Prediction1

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1])

In [55]:
Prediction2=clf_d.predict([[3,125,68,30,120,37,0.4,28]])

In [56]:
Prediction2

array([0])

In [65]:
X_new =[[3,125,68,30,120,37,0.4,28]]

In [66]:
Prediction2=clf_d.predict(X_new)

In [60]:
Prediction2

array([0])